### ISSUE TITLE
Caught exception, writing minidump...

### ISSUE THREAD

**Issue by Pantsi** [Zamiell/racing-plus#1]
Game not starting since a couple of days back. 

Version of racing plus: 0.57.10
Game is Afterbirth+

Gamelog shows following

[INFO] - Failed to load image gfx/ui/boss/ground.png
[INFO] - Failed to load image gfx/ui/stage/playerportrait_isaac.png
[INFO] - Failed to load image gfx/ui/boss/overlay.png
[INFO] - Failed to load image gfx/ui/stage/playerportrait_isaac.png
[INFO] - Caught exception, writing minidump...

Tried to uninstall workshop mod and installing it again, no difference.

**Comment by Pantsi** [comment]
Attaching complete log
[log.txt](https://github.com/Zamiell/racing-plus/files/6546140/log.txt)

**Comment by Pantsi** [comment]
Nope, not owning repentance. Running on afterbirth+

**Comment by Zamiell** [comment]
Are you subscribed to the mod on the steam workshop?

**Comment by Pantsi** [comment]
Yes, verified my game files and tried to uninstall and reinstall the workshop mod.
It stopped working for me and my friend 2-4 days ago. My friend disable mods for the game in the ini file and it started working. 
Also this is the only mod i have installed for the game right now.

**Comment by Zamiell** [comment]
if you are subscribed to the mod on the steam workshop, that's your problem, because the current version of racing+ is for repentance.

either buy repentance, or unsub from the mod from the steam workshop and manually install the specific old version that you want

**Comment by Pantsi** [comment]
Thanks :)
